version: 0.2

phases:
  pre_build:
    commands:
      - aws s3 cp "s3://adnan-demo-s3/adnan_resume.pdf" .
      - echo "Reading resume"
      - cat adnan_resume.pdf

  build:
    commands:
      - ./gradlew clean assembleDebug
      
artifacts:
  files:
    - app/build/outputs/apk/debug/app-debug.apk
